//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backendLuisGiron.WSOnline {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoVariable", Namespace="http://www.banguat.gob.gt/variables/ws/")]
    [System.SerializableAttribute()]
    public partial class InfoVariable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private backendLuisGiron.WSOnline.Variable[] VariablesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private backendLuisGiron.WSOnline.Var[] CambioDiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private backendLuisGiron.WSOnline.VarDolar[] CambioDolarField;
        
        private int TotalItemsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public backendLuisGiron.WSOnline.Variable[] Variables {
            get {
                return this.VariablesField;
            }
            set {
                if ((object.ReferenceEquals(this.VariablesField, value) != true)) {
                    this.VariablesField = value;
                    this.RaisePropertyChanged("Variables");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public backendLuisGiron.WSOnline.Var[] CambioDia {
            get {
                return this.CambioDiaField;
            }
            set {
                if ((object.ReferenceEquals(this.CambioDiaField, value) != true)) {
                    this.CambioDiaField = value;
                    this.RaisePropertyChanged("CambioDia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public backendLuisGiron.WSOnline.VarDolar[] CambioDolar {
            get {
                return this.CambioDolarField;
            }
            set {
                if ((object.ReferenceEquals(this.CambioDolarField, value) != true)) {
                    this.CambioDolarField = value;
                    this.RaisePropertyChanged("CambioDolar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int TotalItems {
            get {
                return this.TotalItemsField;
            }
            set {
                if ((this.TotalItemsField.Equals(value) != true)) {
                    this.TotalItemsField = value;
                    this.RaisePropertyChanged("TotalItems");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Variable", Namespace="http://www.banguat.gob.gt/variables/ws/")]
    [System.SerializableAttribute()]
    public partial class Variable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int monedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int moneda {
            get {
                return this.monedaField;
            }
            set {
                if ((this.monedaField.Equals(value) != true)) {
                    this.monedaField = value;
                    this.RaisePropertyChanged("moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Var", Namespace="http://www.banguat.gob.gt/variables/ws/")]
    [System.SerializableAttribute()]
    public partial class Var : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int monedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fechaField;
        
        private float ventaField;
        
        private float compraField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int moneda {
            get {
                return this.monedaField;
            }
            set {
                if ((this.monedaField.Equals(value) != true)) {
                    this.monedaField = value;
                    this.RaisePropertyChanged("moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaField, value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public float venta {
            get {
                return this.ventaField;
            }
            set {
                if ((this.ventaField.Equals(value) != true)) {
                    this.ventaField = value;
                    this.RaisePropertyChanged("venta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public float compra {
            get {
                return this.compraField;
            }
            set {
                if ((this.compraField.Equals(value) != true)) {
                    this.compraField = value;
                    this.RaisePropertyChanged("compra");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VarDolar", Namespace="http://www.banguat.gob.gt/variables/ws/")]
    [System.SerializableAttribute()]
    public partial class VarDolar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fechaField;
        
        private float referenciaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaField, value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public float referencia {
            get {
                return this.referenciaField;
            }
            set {
                if ((this.referenciaField.Equals(value) != true)) {
                    this.referenciaField = value;
                    this.RaisePropertyChanged("referencia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataVariable", Namespace="http://www.banguat.gob.gt/variables/ws/")]
    [System.SerializableAttribute()]
    public partial class DataVariable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private backendLuisGiron.WSOnline.Var[] VarsField;
        
        private int TotalItemsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public backendLuisGiron.WSOnline.Var[] Vars {
            get {
                return this.VarsField;
            }
            set {
                if ((object.ReferenceEquals(this.VarsField, value) != true)) {
                    this.VarsField = value;
                    this.RaisePropertyChanged("Vars");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int TotalItems {
            get {
                return this.TotalItemsField;
            }
            set {
                if ((this.TotalItemsField.Equals(value) != true)) {
                    this.TotalItemsField = value;
                    this.RaisePropertyChanged("TotalItems");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/", ConfigurationName="WSOnline.TipoCambioSoap")]
    public interface TipoCambioSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento VariablesDisponiblesResult del espacio de nombres http://www.banguat.gob.gt/variables/ws/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/VariablesDisponibles", ReplyAction="*")]
        backendLuisGiron.WSOnline.VariablesDisponiblesResponse VariablesDisponibles(backendLuisGiron.WSOnline.VariablesDisponiblesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/VariablesDisponibles", ReplyAction="*")]
        System.Threading.Tasks.Task<backendLuisGiron.WSOnline.VariablesDisponiblesResponse> VariablesDisponiblesAsync(backendLuisGiron.WSOnline.VariablesDisponiblesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento VariablesResult del espacio de nombres http://www.banguat.gob.gt/variables/ws/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/Variables", ReplyAction="*")]
        backendLuisGiron.WSOnline.VariablesResponse Variables(backendLuisGiron.WSOnline.VariablesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/Variables", ReplyAction="*")]
        System.Threading.Tasks.Task<backendLuisGiron.WSOnline.VariablesResponse> VariablesAsync(backendLuisGiron.WSOnline.VariablesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fechainit del espacio de nombres http://www.banguat.gob.gt/variables/ws/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioFechaInicial", ReplyAction="*")]
        backendLuisGiron.WSOnline.TipoCambioFechaInicialResponse TipoCambioFechaInicial(backendLuisGiron.WSOnline.TipoCambioFechaInicialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioFechaInicial", ReplyAction="*")]
        System.Threading.Tasks.Task<backendLuisGiron.WSOnline.TipoCambioFechaInicialResponse> TipoCambioFechaInicialAsync(backendLuisGiron.WSOnline.TipoCambioFechaInicialRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fechainit del espacio de nombres http://www.banguat.gob.gt/variables/ws/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioRango", ReplyAction="*")]
        backendLuisGiron.WSOnline.TipoCambioRangoResponse TipoCambioRango(backendLuisGiron.WSOnline.TipoCambioRangoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioRango", ReplyAction="*")]
        System.Threading.Tasks.Task<backendLuisGiron.WSOnline.TipoCambioRangoResponse> TipoCambioRangoAsync(backendLuisGiron.WSOnline.TipoCambioRangoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fechainit del espacio de nombres http://www.banguat.gob.gt/variables/ws/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioFechaInicialMoneda", ReplyAction="*")]
        backendLuisGiron.WSOnline.TipoCambioFechaInicialMonedaResponse TipoCambioFechaInicialMoneda(backendLuisGiron.WSOnline.TipoCambioFechaInicialMonedaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioFechaInicialMoneda", ReplyAction="*")]
        System.Threading.Tasks.Task<backendLuisGiron.WSOnline.TipoCambioFechaInicialMonedaResponse> TipoCambioFechaInicialMonedaAsync(backendLuisGiron.WSOnline.TipoCambioFechaInicialMonedaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fechainit del espacio de nombres http://www.banguat.gob.gt/variables/ws/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioRangoMoneda", ReplyAction="*")]
        backendLuisGiron.WSOnline.TipoCambioRangoMonedaResponse TipoCambioRangoMoneda(backendLuisGiron.WSOnline.TipoCambioRangoMonedaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioRangoMoneda", ReplyAction="*")]
        System.Threading.Tasks.Task<backendLuisGiron.WSOnline.TipoCambioRangoMonedaResponse> TipoCambioRangoMonedaAsync(backendLuisGiron.WSOnline.TipoCambioRangoMonedaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento TipoCambioDiaResult del espacio de nombres http://www.banguat.gob.gt/variables/ws/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioDia", ReplyAction="*")]
        backendLuisGiron.WSOnline.TipoCambioDiaResponse TipoCambioDia(backendLuisGiron.WSOnline.TipoCambioDiaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioDia", ReplyAction="*")]
        System.Threading.Tasks.Task<backendLuisGiron.WSOnline.TipoCambioDiaResponse> TipoCambioDiaAsync(backendLuisGiron.WSOnline.TipoCambioDiaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento TipoCambioDiaStringResult del espacio de nombres http://www.banguat.gob.gt/variables/ws/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioDiaString", ReplyAction="*")]
        backendLuisGiron.WSOnline.TipoCambioDiaStringResponse TipoCambioDiaString(backendLuisGiron.WSOnline.TipoCambioDiaStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioDiaString", ReplyAction="*")]
        System.Threading.Tasks.Task<backendLuisGiron.WSOnline.TipoCambioDiaStringResponse> TipoCambioDiaStringAsync(backendLuisGiron.WSOnline.TipoCambioDiaStringRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VariablesDisponiblesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VariablesDisponibles", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public backendLuisGiron.WSOnline.VariablesDisponiblesRequestBody Body;
        
        public VariablesDisponiblesRequest() {
        }
        
        public VariablesDisponiblesRequest(backendLuisGiron.WSOnline.VariablesDisponiblesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class VariablesDisponiblesRequestBody {
        
        public VariablesDisponiblesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VariablesDisponiblesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VariablesDisponiblesResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public backendLuisGiron.WSOnline.VariablesDisponiblesResponseBody Body;
        
        public VariablesDisponiblesResponse() {
        }
        
        public VariablesDisponiblesResponse(backendLuisGiron.WSOnline.VariablesDisponiblesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class VariablesDisponiblesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public backendLuisGiron.WSOnline.InfoVariable VariablesDisponiblesResult;
        
        public VariablesDisponiblesResponseBody() {
        }
        
        public VariablesDisponiblesResponseBody(backendLuisGiron.WSOnline.InfoVariable VariablesDisponiblesResult) {
            this.VariablesDisponiblesResult = VariablesDisponiblesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VariablesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Variables", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public backendLuisGiron.WSOnline.VariablesRequestBody Body;
        
        public VariablesRequest() {
        }
        
        public VariablesRequest(backendLuisGiron.WSOnline.VariablesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class VariablesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int variable;
        
        public VariablesRequestBody() {
        }
        
        public VariablesRequestBody(int variable) {
            this.variable = variable;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VariablesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VariablesResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public backendLuisGiron.WSOnline.VariablesResponseBody Body;
        
        public VariablesResponse() {
        }
        
        public VariablesResponse(backendLuisGiron.WSOnline.VariablesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class VariablesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public backendLuisGiron.WSOnline.InfoVariable VariablesResult;
        
        public VariablesResponseBody() {
        }
        
        public VariablesResponseBody(backendLuisGiron.WSOnline.InfoVariable VariablesResult) {
            this.VariablesResult = VariablesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioFechaInicialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioFechaInicial", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public backendLuisGiron.WSOnline.TipoCambioFechaInicialRequestBody Body;
        
        public TipoCambioFechaInicialRequest() {
        }
        
        public TipoCambioFechaInicialRequest(backendLuisGiron.WSOnline.TipoCambioFechaInicialRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioFechaInicialRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fechainit;
        
        public TipoCambioFechaInicialRequestBody() {
        }
        
        public TipoCambioFechaInicialRequestBody(string fechainit) {
            this.fechainit = fechainit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioFechaInicialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioFechaInicialResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public backendLuisGiron.WSOnline.TipoCambioFechaInicialResponseBody Body;
        
        public TipoCambioFechaInicialResponse() {
        }
        
        public TipoCambioFechaInicialResponse(backendLuisGiron.WSOnline.TipoCambioFechaInicialResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioFechaInicialResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public backendLuisGiron.WSOnline.DataVariable TipoCambioFechaInicialResult;
        
        public TipoCambioFechaInicialResponseBody() {
        }
        
        public TipoCambioFechaInicialResponseBody(backendLuisGiron.WSOnline.DataVariable TipoCambioFechaInicialResult) {
            this.TipoCambioFechaInicialResult = TipoCambioFechaInicialResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioRangoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioRango", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public backendLuisGiron.WSOnline.TipoCambioRangoRequestBody Body;
        
        public TipoCambioRangoRequest() {
        }
        
        public TipoCambioRangoRequest(backendLuisGiron.WSOnline.TipoCambioRangoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioRangoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fechainit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fechafin;
        
        public TipoCambioRangoRequestBody() {
        }
        
        public TipoCambioRangoRequestBody(string fechainit, string fechafin) {
            this.fechainit = fechainit;
            this.fechafin = fechafin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioRangoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioRangoResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public backendLuisGiron.WSOnline.TipoCambioRangoResponseBody Body;
        
        public TipoCambioRangoResponse() {
        }
        
        public TipoCambioRangoResponse(backendLuisGiron.WSOnline.TipoCambioRangoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioRangoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public backendLuisGiron.WSOnline.DataVariable TipoCambioRangoResult;
        
        public TipoCambioRangoResponseBody() {
        }
        
        public TipoCambioRangoResponseBody(backendLuisGiron.WSOnline.DataVariable TipoCambioRangoResult) {
            this.TipoCambioRangoResult = TipoCambioRangoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioFechaInicialMonedaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioFechaInicialMoneda", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public backendLuisGiron.WSOnline.TipoCambioFechaInicialMonedaRequestBody Body;
        
        public TipoCambioFechaInicialMonedaRequest() {
        }
        
        public TipoCambioFechaInicialMonedaRequest(backendLuisGiron.WSOnline.TipoCambioFechaInicialMonedaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioFechaInicialMonedaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fechainit;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int moneda;
        
        public TipoCambioFechaInicialMonedaRequestBody() {
        }
        
        public TipoCambioFechaInicialMonedaRequestBody(string fechainit, int moneda) {
            this.fechainit = fechainit;
            this.moneda = moneda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioFechaInicialMonedaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioFechaInicialMonedaResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public backendLuisGiron.WSOnline.TipoCambioFechaInicialMonedaResponseBody Body;
        
        public TipoCambioFechaInicialMonedaResponse() {
        }
        
        public TipoCambioFechaInicialMonedaResponse(backendLuisGiron.WSOnline.TipoCambioFechaInicialMonedaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioFechaInicialMonedaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public backendLuisGiron.WSOnline.DataVariable TipoCambioFechaInicialMonedaResult;
        
        public TipoCambioFechaInicialMonedaResponseBody() {
        }
        
        public TipoCambioFechaInicialMonedaResponseBody(backendLuisGiron.WSOnline.DataVariable TipoCambioFechaInicialMonedaResult) {
            this.TipoCambioFechaInicialMonedaResult = TipoCambioFechaInicialMonedaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioRangoMonedaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioRangoMoneda", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public backendLuisGiron.WSOnline.TipoCambioRangoMonedaRequestBody Body;
        
        public TipoCambioRangoMonedaRequest() {
        }
        
        public TipoCambioRangoMonedaRequest(backendLuisGiron.WSOnline.TipoCambioRangoMonedaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioRangoMonedaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fechainit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fechafin;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int moneda;
        
        public TipoCambioRangoMonedaRequestBody() {
        }
        
        public TipoCambioRangoMonedaRequestBody(string fechainit, string fechafin, int moneda) {
            this.fechainit = fechainit;
            this.fechafin = fechafin;
            this.moneda = moneda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioRangoMonedaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioRangoMonedaResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public backendLuisGiron.WSOnline.TipoCambioRangoMonedaResponseBody Body;
        
        public TipoCambioRangoMonedaResponse() {
        }
        
        public TipoCambioRangoMonedaResponse(backendLuisGiron.WSOnline.TipoCambioRangoMonedaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioRangoMonedaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public backendLuisGiron.WSOnline.DataVariable TipoCambioRangoMonedaResult;
        
        public TipoCambioRangoMonedaResponseBody() {
        }
        
        public TipoCambioRangoMonedaResponseBody(backendLuisGiron.WSOnline.DataVariable TipoCambioRangoMonedaResult) {
            this.TipoCambioRangoMonedaResult = TipoCambioRangoMonedaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioDiaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioDia", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public backendLuisGiron.WSOnline.TipoCambioDiaRequestBody Body;
        
        public TipoCambioDiaRequest() {
        }
        
        public TipoCambioDiaRequest(backendLuisGiron.WSOnline.TipoCambioDiaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TipoCambioDiaRequestBody {
        
        public TipoCambioDiaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioDiaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioDiaResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public backendLuisGiron.WSOnline.TipoCambioDiaResponseBody Body;
        
        public TipoCambioDiaResponse() {
        }
        
        public TipoCambioDiaResponse(backendLuisGiron.WSOnline.TipoCambioDiaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioDiaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public backendLuisGiron.WSOnline.InfoVariable TipoCambioDiaResult;
        
        public TipoCambioDiaResponseBody() {
        }
        
        public TipoCambioDiaResponseBody(backendLuisGiron.WSOnline.InfoVariable TipoCambioDiaResult) {
            this.TipoCambioDiaResult = TipoCambioDiaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioDiaStringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioDiaString", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public backendLuisGiron.WSOnline.TipoCambioDiaStringRequestBody Body;
        
        public TipoCambioDiaStringRequest() {
        }
        
        public TipoCambioDiaStringRequest(backendLuisGiron.WSOnline.TipoCambioDiaStringRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TipoCambioDiaStringRequestBody {
        
        public TipoCambioDiaStringRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioDiaStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioDiaStringResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public backendLuisGiron.WSOnline.TipoCambioDiaStringResponseBody Body;
        
        public TipoCambioDiaStringResponse() {
        }
        
        public TipoCambioDiaStringResponse(backendLuisGiron.WSOnline.TipoCambioDiaStringResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioDiaStringResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TipoCambioDiaStringResult;
        
        public TipoCambioDiaStringResponseBody() {
        }
        
        public TipoCambioDiaStringResponseBody(string TipoCambioDiaStringResult) {
            this.TipoCambioDiaStringResult = TipoCambioDiaStringResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TipoCambioSoapChannel : backendLuisGiron.WSOnline.TipoCambioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TipoCambioSoapClient : System.ServiceModel.ClientBase<backendLuisGiron.WSOnline.TipoCambioSoap>, backendLuisGiron.WSOnline.TipoCambioSoap {
        
        public TipoCambioSoapClient() {
        }
        
        public TipoCambioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TipoCambioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TipoCambioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TipoCambioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        backendLuisGiron.WSOnline.VariablesDisponiblesResponse backendLuisGiron.WSOnline.TipoCambioSoap.VariablesDisponibles(backendLuisGiron.WSOnline.VariablesDisponiblesRequest request) {
            return base.Channel.VariablesDisponibles(request);
        }
        
        public backendLuisGiron.WSOnline.InfoVariable VariablesDisponibles() {
            backendLuisGiron.WSOnline.VariablesDisponiblesRequest inValue = new backendLuisGiron.WSOnline.VariablesDisponiblesRequest();
            inValue.Body = new backendLuisGiron.WSOnline.VariablesDisponiblesRequestBody();
            backendLuisGiron.WSOnline.VariablesDisponiblesResponse retVal = ((backendLuisGiron.WSOnline.TipoCambioSoap)(this)).VariablesDisponibles(inValue);
            return retVal.Body.VariablesDisponiblesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<backendLuisGiron.WSOnline.VariablesDisponiblesResponse> backendLuisGiron.WSOnline.TipoCambioSoap.VariablesDisponiblesAsync(backendLuisGiron.WSOnline.VariablesDisponiblesRequest request) {
            return base.Channel.VariablesDisponiblesAsync(request);
        }
        
        public System.Threading.Tasks.Task<backendLuisGiron.WSOnline.VariablesDisponiblesResponse> VariablesDisponiblesAsync() {
            backendLuisGiron.WSOnline.VariablesDisponiblesRequest inValue = new backendLuisGiron.WSOnline.VariablesDisponiblesRequest();
            inValue.Body = new backendLuisGiron.WSOnline.VariablesDisponiblesRequestBody();
            return ((backendLuisGiron.WSOnline.TipoCambioSoap)(this)).VariablesDisponiblesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        backendLuisGiron.WSOnline.VariablesResponse backendLuisGiron.WSOnline.TipoCambioSoap.Variables(backendLuisGiron.WSOnline.VariablesRequest request) {
            return base.Channel.Variables(request);
        }
        
        public backendLuisGiron.WSOnline.InfoVariable Variables(int variable) {
            backendLuisGiron.WSOnline.VariablesRequest inValue = new backendLuisGiron.WSOnline.VariablesRequest();
            inValue.Body = new backendLuisGiron.WSOnline.VariablesRequestBody();
            inValue.Body.variable = variable;
            backendLuisGiron.WSOnline.VariablesResponse retVal = ((backendLuisGiron.WSOnline.TipoCambioSoap)(this)).Variables(inValue);
            return retVal.Body.VariablesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<backendLuisGiron.WSOnline.VariablesResponse> backendLuisGiron.WSOnline.TipoCambioSoap.VariablesAsync(backendLuisGiron.WSOnline.VariablesRequest request) {
            return base.Channel.VariablesAsync(request);
        }
        
        public System.Threading.Tasks.Task<backendLuisGiron.WSOnline.VariablesResponse> VariablesAsync(int variable) {
            backendLuisGiron.WSOnline.VariablesRequest inValue = new backendLuisGiron.WSOnline.VariablesRequest();
            inValue.Body = new backendLuisGiron.WSOnline.VariablesRequestBody();
            inValue.Body.variable = variable;
            return ((backendLuisGiron.WSOnline.TipoCambioSoap)(this)).VariablesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        backendLuisGiron.WSOnline.TipoCambioFechaInicialResponse backendLuisGiron.WSOnline.TipoCambioSoap.TipoCambioFechaInicial(backendLuisGiron.WSOnline.TipoCambioFechaInicialRequest request) {
            return base.Channel.TipoCambioFechaInicial(request);
        }
        
        public backendLuisGiron.WSOnline.DataVariable TipoCambioFechaInicial(string fechainit) {
            backendLuisGiron.WSOnline.TipoCambioFechaInicialRequest inValue = new backendLuisGiron.WSOnline.TipoCambioFechaInicialRequest();
            inValue.Body = new backendLuisGiron.WSOnline.TipoCambioFechaInicialRequestBody();
            inValue.Body.fechainit = fechainit;
            backendLuisGiron.WSOnline.TipoCambioFechaInicialResponse retVal = ((backendLuisGiron.WSOnline.TipoCambioSoap)(this)).TipoCambioFechaInicial(inValue);
            return retVal.Body.TipoCambioFechaInicialResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<backendLuisGiron.WSOnline.TipoCambioFechaInicialResponse> backendLuisGiron.WSOnline.TipoCambioSoap.TipoCambioFechaInicialAsync(backendLuisGiron.WSOnline.TipoCambioFechaInicialRequest request) {
            return base.Channel.TipoCambioFechaInicialAsync(request);
        }
        
        public System.Threading.Tasks.Task<backendLuisGiron.WSOnline.TipoCambioFechaInicialResponse> TipoCambioFechaInicialAsync(string fechainit) {
            backendLuisGiron.WSOnline.TipoCambioFechaInicialRequest inValue = new backendLuisGiron.WSOnline.TipoCambioFechaInicialRequest();
            inValue.Body = new backendLuisGiron.WSOnline.TipoCambioFechaInicialRequestBody();
            inValue.Body.fechainit = fechainit;
            return ((backendLuisGiron.WSOnline.TipoCambioSoap)(this)).TipoCambioFechaInicialAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        backendLuisGiron.WSOnline.TipoCambioRangoResponse backendLuisGiron.WSOnline.TipoCambioSoap.TipoCambioRango(backendLuisGiron.WSOnline.TipoCambioRangoRequest request) {
            return base.Channel.TipoCambioRango(request);
        }
        
        public backendLuisGiron.WSOnline.DataVariable TipoCambioRango(string fechainit, string fechafin) {
            backendLuisGiron.WSOnline.TipoCambioRangoRequest inValue = new backendLuisGiron.WSOnline.TipoCambioRangoRequest();
            inValue.Body = new backendLuisGiron.WSOnline.TipoCambioRangoRequestBody();
            inValue.Body.fechainit = fechainit;
            inValue.Body.fechafin = fechafin;
            backendLuisGiron.WSOnline.TipoCambioRangoResponse retVal = ((backendLuisGiron.WSOnline.TipoCambioSoap)(this)).TipoCambioRango(inValue);
            return retVal.Body.TipoCambioRangoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<backendLuisGiron.WSOnline.TipoCambioRangoResponse> backendLuisGiron.WSOnline.TipoCambioSoap.TipoCambioRangoAsync(backendLuisGiron.WSOnline.TipoCambioRangoRequest request) {
            return base.Channel.TipoCambioRangoAsync(request);
        }
        
        public System.Threading.Tasks.Task<backendLuisGiron.WSOnline.TipoCambioRangoResponse> TipoCambioRangoAsync(string fechainit, string fechafin) {
            backendLuisGiron.WSOnline.TipoCambioRangoRequest inValue = new backendLuisGiron.WSOnline.TipoCambioRangoRequest();
            inValue.Body = new backendLuisGiron.WSOnline.TipoCambioRangoRequestBody();
            inValue.Body.fechainit = fechainit;
            inValue.Body.fechafin = fechafin;
            return ((backendLuisGiron.WSOnline.TipoCambioSoap)(this)).TipoCambioRangoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        backendLuisGiron.WSOnline.TipoCambioFechaInicialMonedaResponse backendLuisGiron.WSOnline.TipoCambioSoap.TipoCambioFechaInicialMoneda(backendLuisGiron.WSOnline.TipoCambioFechaInicialMonedaRequest request) {
            return base.Channel.TipoCambioFechaInicialMoneda(request);
        }
        
        public backendLuisGiron.WSOnline.DataVariable TipoCambioFechaInicialMoneda(string fechainit, int moneda) {
            backendLuisGiron.WSOnline.TipoCambioFechaInicialMonedaRequest inValue = new backendLuisGiron.WSOnline.TipoCambioFechaInicialMonedaRequest();
            inValue.Body = new backendLuisGiron.WSOnline.TipoCambioFechaInicialMonedaRequestBody();
            inValue.Body.fechainit = fechainit;
            inValue.Body.moneda = moneda;
            backendLuisGiron.WSOnline.TipoCambioFechaInicialMonedaResponse retVal = ((backendLuisGiron.WSOnline.TipoCambioSoap)(this)).TipoCambioFechaInicialMoneda(inValue);
            return retVal.Body.TipoCambioFechaInicialMonedaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<backendLuisGiron.WSOnline.TipoCambioFechaInicialMonedaResponse> backendLuisGiron.WSOnline.TipoCambioSoap.TipoCambioFechaInicialMonedaAsync(backendLuisGiron.WSOnline.TipoCambioFechaInicialMonedaRequest request) {
            return base.Channel.TipoCambioFechaInicialMonedaAsync(request);
        }
        
        public System.Threading.Tasks.Task<backendLuisGiron.WSOnline.TipoCambioFechaInicialMonedaResponse> TipoCambioFechaInicialMonedaAsync(string fechainit, int moneda) {
            backendLuisGiron.WSOnline.TipoCambioFechaInicialMonedaRequest inValue = new backendLuisGiron.WSOnline.TipoCambioFechaInicialMonedaRequest();
            inValue.Body = new backendLuisGiron.WSOnline.TipoCambioFechaInicialMonedaRequestBody();
            inValue.Body.fechainit = fechainit;
            inValue.Body.moneda = moneda;
            return ((backendLuisGiron.WSOnline.TipoCambioSoap)(this)).TipoCambioFechaInicialMonedaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        backendLuisGiron.WSOnline.TipoCambioRangoMonedaResponse backendLuisGiron.WSOnline.TipoCambioSoap.TipoCambioRangoMoneda(backendLuisGiron.WSOnline.TipoCambioRangoMonedaRequest request) {
            return base.Channel.TipoCambioRangoMoneda(request);
        }
        
        public backendLuisGiron.WSOnline.DataVariable TipoCambioRangoMoneda(string fechainit, string fechafin, int moneda) {
            backendLuisGiron.WSOnline.TipoCambioRangoMonedaRequest inValue = new backendLuisGiron.WSOnline.TipoCambioRangoMonedaRequest();
            inValue.Body = new backendLuisGiron.WSOnline.TipoCambioRangoMonedaRequestBody();
            inValue.Body.fechainit = fechainit;
            inValue.Body.fechafin = fechafin;
            inValue.Body.moneda = moneda;
            backendLuisGiron.WSOnline.TipoCambioRangoMonedaResponse retVal = ((backendLuisGiron.WSOnline.TipoCambioSoap)(this)).TipoCambioRangoMoneda(inValue);
            return retVal.Body.TipoCambioRangoMonedaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<backendLuisGiron.WSOnline.TipoCambioRangoMonedaResponse> backendLuisGiron.WSOnline.TipoCambioSoap.TipoCambioRangoMonedaAsync(backendLuisGiron.WSOnline.TipoCambioRangoMonedaRequest request) {
            return base.Channel.TipoCambioRangoMonedaAsync(request);
        }
        
        public System.Threading.Tasks.Task<backendLuisGiron.WSOnline.TipoCambioRangoMonedaResponse> TipoCambioRangoMonedaAsync(string fechainit, string fechafin, int moneda) {
            backendLuisGiron.WSOnline.TipoCambioRangoMonedaRequest inValue = new backendLuisGiron.WSOnline.TipoCambioRangoMonedaRequest();
            inValue.Body = new backendLuisGiron.WSOnline.TipoCambioRangoMonedaRequestBody();
            inValue.Body.fechainit = fechainit;
            inValue.Body.fechafin = fechafin;
            inValue.Body.moneda = moneda;
            return ((backendLuisGiron.WSOnline.TipoCambioSoap)(this)).TipoCambioRangoMonedaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        backendLuisGiron.WSOnline.TipoCambioDiaResponse backendLuisGiron.WSOnline.TipoCambioSoap.TipoCambioDia(backendLuisGiron.WSOnline.TipoCambioDiaRequest request) {
            return base.Channel.TipoCambioDia(request);
        }
        
        public backendLuisGiron.WSOnline.InfoVariable TipoCambioDia() {
            backendLuisGiron.WSOnline.TipoCambioDiaRequest inValue = new backendLuisGiron.WSOnline.TipoCambioDiaRequest();
            inValue.Body = new backendLuisGiron.WSOnline.TipoCambioDiaRequestBody();
            backendLuisGiron.WSOnline.TipoCambioDiaResponse retVal = ((backendLuisGiron.WSOnline.TipoCambioSoap)(this)).TipoCambioDia(inValue);
            return retVal.Body.TipoCambioDiaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<backendLuisGiron.WSOnline.TipoCambioDiaResponse> backendLuisGiron.WSOnline.TipoCambioSoap.TipoCambioDiaAsync(backendLuisGiron.WSOnline.TipoCambioDiaRequest request) {
            return base.Channel.TipoCambioDiaAsync(request);
        }
        
        public System.Threading.Tasks.Task<backendLuisGiron.WSOnline.TipoCambioDiaResponse> TipoCambioDiaAsync() {
            backendLuisGiron.WSOnline.TipoCambioDiaRequest inValue = new backendLuisGiron.WSOnline.TipoCambioDiaRequest();
            inValue.Body = new backendLuisGiron.WSOnline.TipoCambioDiaRequestBody();
            return ((backendLuisGiron.WSOnline.TipoCambioSoap)(this)).TipoCambioDiaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        backendLuisGiron.WSOnline.TipoCambioDiaStringResponse backendLuisGiron.WSOnline.TipoCambioSoap.TipoCambioDiaString(backendLuisGiron.WSOnline.TipoCambioDiaStringRequest request) {
            return base.Channel.TipoCambioDiaString(request);
        }
        
        public string TipoCambioDiaString() {
            backendLuisGiron.WSOnline.TipoCambioDiaStringRequest inValue = new backendLuisGiron.WSOnline.TipoCambioDiaStringRequest();
            inValue.Body = new backendLuisGiron.WSOnline.TipoCambioDiaStringRequestBody();
            backendLuisGiron.WSOnline.TipoCambioDiaStringResponse retVal = ((backendLuisGiron.WSOnline.TipoCambioSoap)(this)).TipoCambioDiaString(inValue);
            return retVal.Body.TipoCambioDiaStringResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<backendLuisGiron.WSOnline.TipoCambioDiaStringResponse> backendLuisGiron.WSOnline.TipoCambioSoap.TipoCambioDiaStringAsync(backendLuisGiron.WSOnline.TipoCambioDiaStringRequest request) {
            return base.Channel.TipoCambioDiaStringAsync(request);
        }
        
        public System.Threading.Tasks.Task<backendLuisGiron.WSOnline.TipoCambioDiaStringResponse> TipoCambioDiaStringAsync() {
            backendLuisGiron.WSOnline.TipoCambioDiaStringRequest inValue = new backendLuisGiron.WSOnline.TipoCambioDiaStringRequest();
            inValue.Body = new backendLuisGiron.WSOnline.TipoCambioDiaStringRequestBody();
            return ((backendLuisGiron.WSOnline.TipoCambioSoap)(this)).TipoCambioDiaStringAsync(inValue);
        }
    }
}
